INSERT INTO series(title, author_id, subgenre_id) VALUES("Hunger Games", 1, 1);
INSERT INTO series(title, author_id, subgenre_id) VALUES("Harry Potter", 2, 2);
INSERT INTO subgenres(name) VALUES("Dystopian");
INSERT INTO subgenres(name) VALUES("Fantasy");
INSERT INTO authors(name) VALUES("Suzanne Collins");
INSERT INTO authors(name) VALUES("J. K. Rowling");
INSERT INTO books(title, year, series_id) VALUES("Hunger Games", 2008, 1);
INSERT INTO books(title, year, series_id) VALUES("Catching Fire", 2009, 1);
INSERT INTO books(title, year, series_id) VALUES("Mockingjay", 2010, 1);
INSERT INTO books(title, year, series_id) VALUES("Philosopher's Stone", 1997, 2);
INSERT INTO books(title, year, series_id) VALUES("The Chamber of Secrets", 1998, 2);
INSERT INTO books(title, year, series_id) VALUES("The Prisoner of Azkaban", 1999, 2);
INSERT INTO characters(name, motto, species, author_id) VALUES("Katniss Everdeen", "I volunteer", "Human", 1);
INSERT INTO characters(name, motto, species, author_id) VALUES("Peeta Mellark", "I love her", "Human", 1);
INSERT INTO characters(name, motto, species, author_id) VALUES("President Snow", "I am in charge", "Human", 1);
INSERT INTO characters(name, motto, species, author_id) VALUES("Haymitch", "I'd rather be drinking", "Human", 1);
INSERT INTO characters(name, motto, species, author_id) VALUES("Harry Potter", "The boy who lives", "Human", 2);
INSERT INTO characters(name, motto, species, author_id) VALUES("Hagrid", "Anything for Dumbledore", "Giant", 2);
INSERT INTO characters(name, motto, species, author_id) VALUES("Doby", "Anything for Harry", "elf", 2);
INSERT INTO characters(name, motto, species, author_id) VALUES("Remus Lupin", "No one can know", "Werewolf", 2);
INSERT INTO character_books(character_id, book_id) VALUES(1, 1);
INSERT INTO character_books(character_id, book_id) VALUES(1, 2);
INSERT INTO character_books(character_id, book_id) VALUES(1, 3);
INSERT INTO character_books(character_id, book_id) VALUES(2, 1);
INSERT INTO character_books(character_id, book_id) VALUES(2, 2);
INSERT INTO character_books(character_id, book_id) VALUES(2, 3);
INSERT INTO character_books(character_id, book_id) VALUES(3, 2);
INSERT INTO character_books(character_id, book_id) VALUES(4, 1);
INSERT INTO character_books(character_id, book_id) VALUES(5, 4);
INSERT INTO character_books(character_id, book_id) VALUES(5, 5);
INSERT INTO character_books(character_id, book_id) VALUES(5, 6);
INSERT INTO character_books(character_id, book_id) VALUES(6, 4);
INSERT INTO character_books(character_id, book_id) VALUES(6, 5);
INSERT INTO character_books(character_id, book_id) VALUES(6, 6);
INSERT INTO character_books(character_id, book_id) VALUES(7, 4);
INSERT INTO character_books(character_id, book_id) VALUES(8, 6);
